global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Screenshot Manager HTTPサーバー
  - job_name: 'screenshot-manager-http'
    static_configs:
      - targets: ['screenshot-manager:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # Screenshot Manager MCPサーバー
  - job_name: 'screenshot-manager-mcp'
    static_configs:
      - targets: ['mcp-server:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis監視
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # システムメトリクス (Node Exporter風)
  - job_name: 'screenshot-manager-system'
    static_configs:
      - targets: ['screenshot-manager:8080']
    metrics_path: '/system-metrics'
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# アラートルール（例）
rule_files:
  - "/etc/prometheus/rules/*.yml"