apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsConfigurationMethod: file-path
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      queryTimeout: 60s
      defaultEditor: code
      disableMetricsLookup: false
      customQueryParameters: ""
    secureJsonData: {}